### ISSUE TITLE
ArrayIndexOutOfBoundsException in iterator.

### ISSUE THREAD

**Issue by svladykin** [nbronson/snaptree#4]
Don't have consistently reproducible test case but it happens with concurrent updates, removes and iterations over snapshots. It seems that sometimes height + 1 is not enough to accommodate full tree branch.

java.lang.ArrayIndexOutOfBoundsException: 5
    at edu.stanford.ppl.concurrent.SnapTreeMap$AbstractIter.pushFirst(SnapTreeMap.java:2062)
    at edu.stanford.ppl.concurrent.SnapTreeMap$AbstractIter.advance(SnapTreeMap.java:2102)
    at edu.stanford.ppl.concurrent.SnapTreeMap$AbstractIter.nextNode(SnapTreeMap.java:2130)
    at edu.stanford.ppl.concurrent.SnapTreeMap$KeyIter.next(SnapTreeMap.java:1976)

**Comment by svladykin** [comment]
Here is the heap dump after the exception in randomized test containing map in state which produced error.
https://docs.google.com/open?id=0B93W_br_IlJmWUp1bGFtRng2czg
Hope this will help to address the issue.

**Comment by nbronson** [comment]
Thanks, the heap dump might be very helpful. I won't be able to work on this during the next week, but I will dig into it as soon as possible

**Comment by svladykin** [comment]
Any news on this issue?

**Comment by nbronson** [comment]
I am working on it, but I have newborn twins so it is hard to achieve the
required mental clarity. I have a repro and a theory.

Thanks for reporting the issues
- Nathan

**Comment by aehusain** [comment]
Hi Nathan,

Is their any update on this issue, we are hitting a similar error but it does not happen consistently:

java.lang.ArrayIndexOutOfBoundsException: 6
at edu.stanford.ppl.concurrent.SnapTreeMap$AbstractIter.pushFirst(SnapTreeMap.java:2062)
at edu.stanford.ppl.concurrent.SnapTreeMap$AbstractIter.advance(SnapTreeMap.java:2102)
at edu.stanford.ppl.concurrent.SnapTreeMap$AbstractIter.nextNode(SnapTreeMap.java:2130)
at edu.stanford.ppl.concurrent.SnapTreeMap$EntryIter.next(SnapTreeMap.java:1956)
at edu.stanford.ppl.concurrent.SnapTreeMap$EntryIter.next(SnapTreeMap.java:1940)

I see the codeline number doesn't match the current github version, please let me know if it is fixed in recent updates.

Thanks!
